# I. NumPy.

**Оцінювання даної роботи буде ураховувати якість Вашого коду та текстових відповідей. При наявності ЛИШЕ коду , робота оцінюватися НЕ БУДЕ.**  

**Оформлення текстових відповідей повинно проводитися в текстових комірках ноутбука з використанням синтаксису [LaTeX](https://en.wikibooks.org/wiki/LaTeX/Basics) для оформлення тексту та формул.**

**Роботи ідентифіковані як ІДЕНТИЧНІ одразу отримують 0 балів.**

**При реалізації завдань потрібно використовувати методи з бібліотеки numpy та pandas.**

**Рішення з циклами будуть оцінені в 0 балів.**

0. Імпортувати numpy загальноприйнятим способом.

In [1]:
import numpy as np 

1. Визначити список з оцінками студента(ки) за семестр. Використовуючи його, створити одновимірний масив numpy.

In [2]:
grades = [59, 98, 63, 92, 88, 70, 51]
grades_array = np.array(grades)

2. Визначити список зі списками, де кожен рядок списку формально означає магазин, а кожна колонка - певний продукт (батон, яйця першої категорії, молоко та ковбаса), а елементами на пересічі є ціни на ці продукти відповідно. Використовуючи цей список, створити матрицю (двовимірний масив) numpy.

In [3]:
prices = [
    [120.0, 220.0, 293.0, 510.0],  # Ціни в Сільпо
    [130.0, 240.0, 295.0, 540.0],  # Ціни в Ашані
    [100.8, 211.0, 254.0, 478.0],  # Ціни в АТБ
]
prices_matrix = np.array(prices)

3. Отримайте тип даних значень з масивів завдань 2 та 3. Виведіть їх на екран.

In [4]:
print("Тип даних у масиві 1:", grades_array.dtype)
print("Тип даних у матриці 2:", prices_matrix.dtype)


Тип даних у масиві 1: int64
Тип даних у матриці 2: float64


4. Отримайте форми (кортеж з кількістю рядків та колонок) масивів завдань 2 та 3. Виведіть їх на екран.

In [5]:
print("Форма масиву 1:", grades_array.shape)
print("Форма матриці 2:", prices_matrix.shape)

Форма масиву 1: (7,)
Форма матриці 2: (3, 4)


5. Створіть одновимірний масив за допомогою спеціальної функції numpy, який би відображав динаміку стабільно зростаючого (з рівними проміжками) прибутку з продажів  за тиждень, де у перший день не було продажів, а в останній день тижня вдалося заробити 1000 грн 50 коп.

In [6]:
start_profit = 0  
end_profit = 1000.50  
days = 7
profit_array = np.linspace(start_profit, end_profit, days)
print("Динаміка прибутку за тиждень (грн):")
print(profit_array)

Динаміка прибутку за тиждень (грн):
[   0.    166.75  333.5   500.25  667.    833.75 1000.5 ]


6. Створіть два масиви. Використовуючи їх, продемонструйте відмінність вертикального та горизонтального обʼєднання масивів.

In [7]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
horizontal_stack = np.hstack((array1, array2))
vertical_stack = np.vstack((array1, array2))
print(horizontal_stack)
print(vertical_stack)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


7. Визначити функцію, яка приймає на вході масив і транспонує його. Скористайтесь методом reshape. І не забудьте почати з docstrings.

In [8]:
def transpose_with_reshape(array):
    if len(array.shape) != 2:
        raise ValueError("Масив має бути двовимірним.")
    rows, cols = array.shape
    return array.reshape(cols, rows).T
array3 = np.array([[1, 2, 3], [4, 5, 6]])
transposed_array = transpose_with_reshape(array3)

print("Оригінальний масив:")
print(array3)

print("\nТранспонований масив:")
print(transposed_array)

Оригінальний масив:
[[1 2 3]
 [4 5 6]]

Транспонований масив:
[[1 3 5]
 [2 4 6]]


8. Створіть два масиви. Використовучи ці масиви, продемонструйте 1) операцію по-елементного додавання, 2) операцію по-елементного віднімання, 3) множення масиву на число, 4) операцію по-елементного множення, і 5) матричного множення.

In [9]:
array4 = np.array([[1, 2, 3], [4, 5, 6]])
array5 = np.array([[6, 5, 4], [3, 2, 1]])
elementwise_addition = array4 + array5
elementwise_subtraction = array4 - array5
scalar_multiplication = array4 * 2
elementwise_multiplication = array4 * array5
matrix_multiplication = np.dot(array4, array5.T)
print("Масив 4:")
print(array4)
print("\nМасив 5:")
print(array5)
print("\n1) По-елементне додавання:")
print(elementwise_addition)
print("\n2) По-елементне віднімання:")
print(elementwise_subtraction)
print("\n3) Множення масиву на число (2):")
print(scalar_multiplication)
print("\n4) По-елементне множення:")
print(elementwise_multiplication)
print("\n5) Матричне множення:")
print(matrix_multiplication)

Масив 4:
[[1 2 3]
 [4 5 6]]

Масив 5:
[[6 5 4]
 [3 2 1]]

1) По-елементне додавання:
[[7 7 7]
 [7 7 7]]

2) По-елементне віднімання:
[[-5 -3 -1]
 [ 1  3  5]]

3) Множення масиву на число (2):
[[ 2  4  6]
 [ 8 10 12]]

4) По-елементне множення:
[[ 6 10 12]
 [12 10  6]]

5) Матричне множення:
[[28 10]
 [73 28]]


9. Створіть двовимірний масив (матрицю) та розрахуйте: 1) мінімальне число, 2) максимальне число, 3) суму чисел, 4) мінімальні числа для кожного рядка, 5) максимальні числа для кожного стовпчика.

In [10]:
matrix = np.random.randint(1, 101, size=(5, 5))
min_value = np.min(matrix)
max_value = np.max(matrix)
sum_values = np.sum(matrix)
min_each_row = np.min(matrix, axis=1)
max_each_column = np.max(matrix, axis=0)
print("Матриця:\n", matrix)
print("Мінімальне число:", min_value)
print("Максимальне число:", max_value)
print("Сума чисел:", sum_values)
print("Мінімальні числа для кожного рядка:", min_each_row)
print("Максимальні числа для кожного стовпчика:", max_each_column)

Матриця:
 [[80 15  7 43 38]
 [97 62 44 52  3]
 [76 59 55 48 30]
 [12  4  2 62 65]
 [20 50  1 84 19]]
Мінімальне число: 1
Максимальне число: 97
Сума чисел: 1028
Мінімальні числа для кожного рядка: [ 7  3 30  2  1]
Максимальні числа для кожного стовпчика: [97 62 55 84 65]


10. Створіть матрицю , де деякі елементи повторюються. Знайдіть унікальні значення елементів цієї матриці та їхні частоти.

In [11]:
matrix_with_duplicates = np.array([[1, 2, 3, 4, 1],
                                   [5, 6, 7, 8, 1],
                                   [9, 2, 3, 4, 5],
                                   [6, 7, 8, 9, 1],
                                   [2, 3, 4, 5, 6]])
unique_values, counts = np.unique(matrix_with_duplicates, return_counts=True)
print("Матриця2:\n", matrix_with_duplicates)
print("Унікальні       значення:", unique_values)
print("Частоти кожного значення:", counts)

Матриця2:
 [[1 2 3 4 1]
 [5 6 7 8 1]
 [9 2 3 4 5]
 [6 7 8 9 1]
 [2 3 4 5 6]]
Унікальні       значення: [1 2 3 4 5 6 7 8 9]
Частоти кожного значення: [4 3 3 3 3 3 2 2 2]


# II. Importing. Creating DF

0. Імпортувати бібліотеку pandas

In [6]:
import pandas as pd

11. Створити тестовий датафрейм зі списку, що містить записи пацієнтів про їхні прізвища, імена, дату народження, масу тіла та наявність медичного страхування. Одне зі значень зробить пустим. Ознайомтесь з типом кожної колонки.

In [7]:
data = [
    ["Язловецький", "Станіслав", "2005-10-01", 66.5, True],
    ["Порошенко", "Петро", "1965-09-26", 92.2, False],
    ["Патрон", "Пес", "2019-07-20", None, True],
    ["Шевцов", "Олексій", "1994-08-12", 34.0, False]
]
columns = ["Прізвище", "Ім'я", "Дата народження", "Маса тіла", "Медичне страхування"]
df = pd.DataFrame(data, columns=columns)
print(df)
print("\nТипи даних у кожному стовпці:")
print(df.dtypes)

      Прізвище       Ім'я Дата народження  Маса тіла  Медичне страхування
0  Язловецький  Станіслав      2005-10-01       66.5                 True
1    Порошенко      Петро      1965-09-26       92.2                False
2       Патрон        Пес      2019-07-20        NaN                 True
3       Шевцов    Олексій      1994-08-12       34.0                False

Типи даних у кожному стовпці:
Прізвище                object
Ім'я                    object
Дата народження         object
Маса тіла              float64
Медичне страхування       bool
dtype: object


# III. Reading from file

12. Завантажити файл missile_attacks_daily.csv з [Kaggle](https://www.kaggle.com/datasets/piterfm/massive-missile-attacks-on-ukraine?select=missile_attacks_daily.csv). Ознайомитись з описом датасету. Додати файл до папки поточної сесії colab notebook на панелі ліворуч або на гугл диск (локально до проєкту, якщо працюєте у пайчармі). Зчитати датафрейм з файлу та вивести датафрейм на екран. Зверніть увагу на те, щоб всі колонки відповідали наведеним у описі типам даних.

In [8]:
file_path = "missile_attacks_daily.csv"
df = pd.read_csv(file_path)
print(df.head())
print("\nТипи даних у кожному стовпці:")
print(df.dtypes)

         time_start          time_end           model  \
0  2025-01-25 19:00  2025-01-26 09:00  Shahed-136/131   
1  2025-01-24 19:00  2025-01-25 09:30  Shahed-136/131   
2  2025-01-24 18:30  2025-01-24 19:30       X-59/X-69   
3  2025-01-23 21:00  2025-01-24 09:00  Shahed-136/131   
4  2025-01-22 19:00  2025-01-23 09:30  Shahed-136/131   

                                        launch_place        target carrier  \
0  Primorsko-Akhtarsk and Kursk oblast and Bryans...       Ukraine     NaN   
1  Primorsko-Akhtarsk and Kursk oblast and Bryans...       Ukraine     NaN   
2                                          Black Sea  Odesa oblast     NaN   
3  Primorsko-Akhtarsk and Kursk oblast and Bryans...       Ukraine     NaN   
4  Primorsko-Akhtarsk and Kursk oblast and Bryans...       Ukraine     NaN   

   launched  destroyed  not_reach_goal  cross_border_belarus  back_russia  \
0      72.0         50             9.0                   NaN          NaN   
1      61.0         46            

# IV. Data understanding

13. Виведіть на екран перші 10 рядків зчитаного датафрейму.

In [9]:
print(df.head(10))

         time_start          time_end             model  \
0  2025-01-25 19:00  2025-01-26 09:00    Shahed-136/131   
1  2025-01-24 19:00  2025-01-25 09:30    Shahed-136/131   
2  2025-01-24 18:30  2025-01-24 19:30         X-59/X-69   
3  2025-01-23 21:00  2025-01-24 09:00    Shahed-136/131   
4  2025-01-22 19:00  2025-01-23 09:30    Shahed-136/131   
5  2025-01-23 04:00  2025-01-23 04:30  Iskander-M/KN-23   
6  2025-01-21 19:00  2025-01-22 10:00    Shahed-136/131   
7  2025-01-20 20:00  2025-01-21 09:00    Shahed-136/131   
8  2025-01-20 20:00  2025-01-21 09:00        Iskander-M   
9  2025-01-19 19:00  2025-01-20 08:00    Shahed-136/131   

                                        launch_place        target carrier  \
0  Primorsko-Akhtarsk and Kursk oblast and Bryans...       Ukraine     NaN   
1  Primorsko-Akhtarsk and Kursk oblast and Bryans...       Ukraine     NaN   
2                                          Black Sea  Odesa oblast     NaN   
3  Primorsko-Akhtarsk and Kursk oblast

14. Отримайте інформацію про форму датафрейму.

In [10]:
print("Форма датафрейму (рядки, колонки):", df.shape)

Форма датафрейму (рядки, колонки): (2056, 16)


15. Отримайте дані про кожну колонку з її назвою, типом даних та кількістю непустих значень.

In [11]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2056 entries, 0 to 2055
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   time_start            2056 non-null   object 
 1   time_end              2056 non-null   object 
 2   model                 2056 non-null   object 
 3   launch_place          1034 non-null   object 
 4   target                2028 non-null   object 
 5   carrier               225 non-null    object 
 6   launched              2053 non-null   float64
 7   destroyed             2056 non-null   int64  
 8   not_reach_goal        164 non-null    float64
 9   cross_border_belarus  32 non-null     float64
 10  back_russia           35 non-null     float64
 11  still_attacking       30 non-null     float64
 12  destroyed_details     301 non-null    object 
 13  launched_details      4 non-null      object 
 14  launch_place_details  4 non-null      object 
 15  source               

16. Отримайте статистику для колонок числового типу.

In [12]:
print(df.describe())

          launched    destroyed  not_reach_goal  cross_border_belarus  \
count  2053.000000  2056.000000      164.000000             32.000000   
mean     10.872382     7.647860       21.231707              2.312500   
std      21.605295    14.506397       19.812804              2.054696   
min       1.000000     0.000000        1.000000              1.000000   
25%       1.000000     1.000000        4.000000              1.000000   
50%       2.000000     1.000000       16.000000              2.000000   
75%       9.000000     7.000000       30.000000              2.000000   
max     193.000000    99.000000      105.000000             10.000000   

       back_russia  still_attacking  
count    35.000000        30.000000  
mean      2.000000         2.766667  
std       1.137593         2.848876  
min       1.000000         1.000000  
25%       1.000000         1.000000  
50%       2.000000         1.000000  
75%       3.000000         3.750000  
max       5.000000        10.000000  


17. Отримати кількість унікальних значень у кожній колонці. Вивести на екран значення та кількість цих значень у колонці, яка має найменше унікальних значень.

In [13]:

unique_counts = df.nunique()
print("Кількість унікальних значень у кожній колонці:\n", unique_counts)

min_unique_col = unique_counts.idxmin()
print(f"\nКолонка з найменшою кількістю унікальних значень: {min_unique_col}")

print(df[min_unique_col].value_counts())

Кількість унікальних значень у кожній колонці:
 time_start               874
time_end                1025
model                     61
launch_place             136
target                    97
carrier                   58
launched                 117
destroyed                 83
not_reach_goal            56
cross_border_belarus       7
back_russia                5
still_attacking            8
destroyed_details        297
launched_details           4
launch_place_details       4
source                   968
dtype: int64

Колонка з найменшою кількістю унікальних значень: launched_details
launched_details
{'X-101/X-555': 50, 'Kalibr': 12}                     1
{'X-101/X-555': 55, 'Kalibr': 24, 'Iskander-K': 7}    1
{'X-101/X-555': 57, 'Kalibr': 28}                     1
{'X-101/X-555': 77, 'Kalibr': 28, 'X-59/X-69': 10}    1
Name: count, dtype: int64


18. На основі отриманої інформації про датасет вище, опишіть по пунктах, що б ви виправили або на що б звернули увагу на кроці очищення даних і чому?

**місце для текстової відповіді**

1.   Пункт списку    Перетворення колонок time_start і time_end у формат datetime
2.   Пункт списку    launched зараз має тип float64, а повинна бути Int64, оскільки число запущених ракет не може бути дробовим.

...


# V. Data Cleaning

19. Перетворити колонку launched у цілочислену (Int64). Перевірити, чи все пройшло, як очікувалось.

In [16]:
df["launched"] = df["launched"].astype("Int64")
print(df.dtypes)

time_start               object
time_end                 object
model                    object
launch_place             object
target                   object
carrier                  object
launched                  Int64
destroyed                 int64
not_reach_goal          float64
cross_border_belarus    float64
back_russia             float64
still_attacking         float64
destroyed_details        object
launched_details         object
launch_place_details     object
source                   object
dtype: object


20. Видалити колонки, де кількість непустих значень становить менше 30% від загальної кількості записів.

In [17]:
threshold = 0.3 * len(df)  
df = df.dropna(axis=1, thresh=threshold)
print("Форма датафрейму після видалення колонок з великою кількістю NaN:", df.shape)

Форма датафрейму після видалення колонок з великою кількістю NaN: (2056, 8)


21. Очистити датафрейм від дублікатів (дублюючихся рядків) та записів, де атака продовжувалась відʼємну або нульову кількість часу (що фізично неможливо). Не забудьте оновити індекс. Скільки рядків було видалено? Як ви це перевірили у коді?

In [21]:
df["time_start"] = pd.to_datetime(df["time_start"], errors='coerce')
df["time_end"] = pd.to_datetime(df["time_end"], errors='coerce')
print("Кількість некоректних дат у time_start:", df["time_start"].isna().sum())
print("Кількість некоректних дат у time_end:", df["time_end"].isna().sum())
df = df.dropna(subset=["time_start", "time_end"])
df["duration"] = (df["time_end"] - df["time_start"]).dt.total_seconds() / 3600
rows_before = len(df)
df = df[df["duration"] > 0]
df = df.reset_index(drop=True)
rows_after = len(df)
print("Кількість видалених рядків:", rows_before - rows_after)

Кількість некоректних дат у time_start: 1446
Кількість некоректних дат у time_end: 678
Кількість видалених рядків: 162


C:\Users\USER\AppData\Local\Temp\ipykernel_24344\561989458.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["duration"] = (df["time_end"] - df["time_start"]).dt.total_seconds() / 3600


**місце для текстової відповіді**

In [ ]:
# Кількість видалених рядків: 162
# порахував рядки до і після видалення дублікатів та некоректних даних, а потім вивів різницю.


22. Виведіть на екран всі рядки, де є хоч одне пропущене значення.

In [20]:
print(df[df.isna().any(axis=1)])

            time_start          time_end               model launch_place  \
11          2025-01-20        2025-01-20            Orlan-10          NaN   
24          2025-01-15        2025-01-15                ZALA          NaN   
25          2025-01-15        2025-01-15            Supercam          NaN   
26          2025-01-15        2025-01-15            Orlan-10          NaN   
27          2025-01-15        2025-01-15              Lancet          NaN   
...                ...               ...                 ...          ...   
2051  2022-10-01 12:00  2022-10-01 12:00            Orlan-10          NaN   
2052        2022-09-30        2022-09-30            Orlan-10          NaN   
2053  2022-09-29 23:00  2022-09-29 23:59      Shahed-136/131          NaN   
2054        2022-09-28        2022-09-28                X-59          NaN   
2055        2022-09-28        2022-09-28  Reconnaissance UAV          NaN   

                                             target  launched  destroyed  \